# backend/Dockerfile.dev
FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy

WORKDIR /app

RUN dotnet tool install -g dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

COPY ./backend/*.csproj ./
RUN dotnet restore

COPY ./backend ./

EXPOSE 5000

CMD ["dotnet", "watch", "run", "--urls=http://0.0.0.0:5000"]
