# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  react-ci:
    name: React Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Build React App
        run: |
          cd frontend
          npm ci
          npm run build

  aspnet-ci:
    name: ASP.NET Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build
        run: |
          cd backend
          dotnet restore
          dotnet build --no-restore

      - name: Test
        run: |
          cd backend
          dotnet test --no-build --verbosity normal
